import 'dart:math' as math;
import 'package:flutter/material.dart';
import '../../core/data/session_model.dart';
import '../../core/exercise/exercise_catalog.dart';
const _purple=Color(0xFF6C5CE7),_ink=Color(0xFF17151F),_muted=Color(0xFF777382);
class ProgressPage extends StatelessWidget{final List<WorkoutSession> sessions;const ProgressPage({super.key,required this.sessions});
 @override Widget build(BuildContext c){final reps=sessions.fold<int>(0,(a,s)=>a+s.reps);final best=sessions.isEmpty?null:sessions.map((s)=>s.bestScore).reduce(math.max);final avg=sessions.isEmpty?null:(sessions.map((s)=>s.averageScore).reduce((a,b)=>a+b)/sessions.length).round();final recent=sessions.take(10).toList();return ListView(padding:const EdgeInsets.all(20),children:[const Text('Progress',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:_ink)),const SizedBox(height:6),const Text('Track every movement, not just one exercise.',style:TextStyle(color:_muted)),const SizedBox(height:22),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(26),border:Border.all(color:const Color(0xFFEDEAF2))),child:Row(children:[_Stat('${sessions.length}','Sessions'),_Stat('$reps','Reps'),_Stat(best==null?'—':'$best','Best'),_Stat(avg==null?'—':'$avg','Average')])),const SizedBox(height:24),const Text('Exercise breakdown',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:_ink)),const SizedBox(height:12),...exerciseCatalog.map((e)=>_ExerciseRow(item:e,sessions:sessions.where((s)=>s.exercise==e.id).toList())),const SizedBox(height:20),const Text('Recent sessions',style:TextStyle(fontSize:20,fontWeight:FontWeight.w900,color:_ink)),const SizedBox(height:12),if(recent.isEmpty)const _Empty() else ...recent.map((s)=>_Session(s))]);}}
class _Stat extends StatelessWidget{final String v,l;const _Stat(this.v,this.l);@override Widget build(BuildContext c)=>Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(v,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:_ink)),const SizedBox(height:3),Text(l,style:const TextStyle(fontSize:10,color:_muted,fontWeight:FontWeight.w700))]));}
class _ExerciseRow extends StatelessWidget{final ExerciseCatalogItem item;final List<WorkoutSession> sessions;const _ExerciseRow({required this.item,required this.sessions});@override Widget build(BuildContext c){final best=sessions.isEmpty?0:sessions.map((s)=>s.bestScore).reduce(math.max);return Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFFEDEAF2))),child:Row(children:[Container(width:46,height:46,decoration:BoxDecoration(color:const Color(0xFFEFEAFF),borderRadius:BorderRadius.circular(14)),child:Icon(item.icon,color:_purple)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item.name,style:const TextStyle(fontWeight:FontWeight.w900,color:_ink)),const SizedBox(height:3),Text(sessions.isEmpty?'Not started':'${sessions.length} sessions • $best best',style:const TextStyle(color:_muted,fontSize:12))])),if(sessions.isNotEmpty)Text('$best',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:18,color:_ink))]));}}
class _Session extends StatelessWidget{final WorkoutSession s;const _Session(this.s);@override Widget build(BuildContext c){final item=exerciseById(s.exercise);return Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFFEDEAF2))),child:Row(children:[Icon(item.icon,color:_purple),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item.name,style:const TextStyle(fontWeight:FontWeight.w900,color:_ink)),Text('${s.reps} reps • ${s.completedAt.day}/${s.completedAt.month}/${s.completedAt.year}',style:const TextStyle(color:_muted,fontSize:12))])),Text('${s.averageScore}',style:const TextStyle(fontWeight:FontWeight.w900,fontSize:19,color:_ink))]));}}
class _Empty extends StatelessWidget{const _Empty();@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:const Color(0xFFEFEAFF),borderRadius:BorderRadius.circular(22)),child:const Text('Complete your first workout to unlock your progress history.',style:TextStyle(color:_ink,fontWeight:FontWeight.w700,height:1.4)));}
