import 'package:flutter/material.dart';
import 'features/pose_check/live_squat_check_page.dart';

const _purple = Color(0xFF6C5CE7);
const _ink = Color(0xFF17151F);
const _muted = Color(0xFF777382);
const _surface = Colors.white;

void main() => runApp(const PoseApp());

class PoseApp extends StatelessWidget {
  const PoseApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'Pose', debugShowCheckedModeBanner: false,
    theme: ThemeData(useMaterial3: true, scaffoldBackgroundColor: const Color(0xFFF7F6FA), colorScheme: ColorScheme.fromSeed(seedColor: _purple), fontFamily: 'sans'),
    home: const HomePage(),
  );
}

class HomePage extends StatefulWidget { const HomePage({super.key}); @override State<HomePage> createState() => _HomePageState(); }
class _HomePageState extends State<HomePage> {
  int index = 0;
  void openCheck() => Navigator.of(context).push(MaterialPageRoute(builder: (_) => const LiveSquatCheckPage()));
  @override Widget build(BuildContext context) {
    final pages = [_Dashboard(onStart: openCheck), _WorkoutsPage(onStart: openCheck), const _ProgressPage(), const _ProfilePage()];
    return Scaffold(body: SafeArea(child: pages[index]), bottomNavigationBar: NavigationBar(height: 72, backgroundColor: _surface, indicatorColor: const Color(0xFFEAE6FF), selectedIndex: index, onDestinationSelected: (v) => setState(() => index = v), destinations: const [
      NavigationDestination(icon: Icon(Icons.home_outlined), selectedIcon: Icon(Icons.home_rounded), label: 'Home'),
      NavigationDestination(icon: Icon(Icons.fitness_center_outlined), selectedIcon: Icon(Icons.fitness_center_rounded), label: 'Train'),
      NavigationDestination(icon: Icon(Icons.insights_outlined), selectedIcon: Icon(Icons.insights_rounded), label: 'Progress'),
      NavigationDestination(icon: Icon(Icons.person_outline_rounded), selectedIcon: Icon(Icons.person_rounded), label: 'Profile'),
    ]));
  }
}

class _Dashboard extends StatelessWidget {
  const _Dashboard({required this.onStart}); final VoidCallback onStart;
  @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.fromLTRB(20, 22, 20, 28), children: [
    Row(children: [Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: const [Text('TODAY', style: TextStyle(fontSize: 12, fontWeight: FontWeight.w800, color: _purple, letterSpacing: 1.4)), SizedBox(height: 5), Text('Ready to move?', style: TextStyle(fontSize: 30, fontWeight: FontWeight.w900, color: _ink, letterSpacing: -.7))])), _IconButton(icon: Icons.notifications_none_rounded)]),
    const SizedBox(height: 22), _HeroCard(onStart: onStart), const SizedBox(height: 26),
    const _SectionHeader(title: 'Today', action: 'Overview'), const SizedBox(height: 12),
    const Row(children: [Expanded(child: _Metric(value: '0', label: 'Sessions', icon: Icons.local_fire_department_outlined)), SizedBox(width: 10), Expanded(child: _Metric(value: '0', label: 'Minutes', icon: Icons.schedule_rounded)), SizedBox(width: 10), Expanded(child: _Metric(value: '—', label: 'Best score', icon: Icons.auto_awesome_outlined))]),
    const SizedBox(height: 28), const _SectionHeader(title: 'Start training', action: ''), const SizedBox(height: 12),
    _TrainingCard(title: 'Squat form', subtitle: 'Technique • 8 min', icon: Icons.directions_run_rounded, onTap: onStart),
    _TrainingCard(title: 'Full body basics', subtitle: 'Beginner • 15 min', icon: Icons.accessibility_new_rounded, onTap: onStart),
    const SizedBox(height: 8), _TipCard(),
  ]);
}

class _IconButton extends StatelessWidget { const _IconButton({required this.icon}); final IconData icon; @override Widget build(BuildContext context) => Container(width: 46, height: 46, decoration: BoxDecoration(color: _surface, borderRadius: BorderRadius.circular(16), boxShadow: const [BoxShadow(color: Color(0x08000000), blurRadius: 12, offset: Offset(0, 4))]), child: Icon(icon, color: _ink)); }
class _TipCard extends StatelessWidget { const _TipCard(); @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: const Color(0xFFEFEAFF), borderRadius: BorderRadius.circular(22)), child: const Row(children: [Icon(Icons.lightbulb_outline_rounded, color: _purple), SizedBox(width: 12), Expanded(child: Text('Tip: keep your full body visible for more accurate feedback.', style: TextStyle(color: _ink, fontWeight: FontWeight.w600, height: 1.3)))])); }

class _HeroCard extends StatelessWidget { const _HeroCard({required this.onStart}); final VoidCallback onStart; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(22), decoration: BoxDecoration(gradient: const LinearGradient(begin: Alignment.topLeft, end: Alignment.bottomRight, colors: [Color(0xFF5E4AD7), Color(0xFF8B79FF)]), borderRadius: BorderRadius.circular(30), boxShadow: [BoxShadow(color: _purple.withValues(alpha: .20), blurRadius: 24, offset: const Offset(0, 10))]), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Row(children: [Container(padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 6), decoration: BoxDecoration(color: Colors.white.withValues(alpha: .16), borderRadius: BorderRadius.circular(30)), child: const Text('AI FORM CHECK', style: TextStyle(color: Colors.white, fontSize: 11, fontWeight: FontWeight.w800, letterSpacing: 1)),), const Spacer(), const Icon(Icons.auto_awesome_rounded, color: Colors.white70, size: 20)]), const SizedBox(height: 18), const Text('Move better.\nFeel stronger.', style: TextStyle(color: Colors.white, fontSize: 30, height: 1.08, fontWeight: FontWeight.w900, letterSpacing: -.7)), const SizedBox(height: 10), const Text('Get instant feedback on your exercise form using your camera.', style: TextStyle(color: Colors.white70, fontSize: 14, height: 1.4)), const SizedBox(height: 20), SizedBox(width: double.infinity, child: FilledButton.icon(onPressed: onStart, icon: const Icon(Icons.camera_alt_rounded), label: const Text('Check my form'), style: FilledButton.styleFrom(backgroundColor: Colors.white, foregroundColor: _purple, padding: const EdgeInsets.symmetric(vertical: 15), shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(16)))))])); }

class _SectionHeader extends StatelessWidget { const _SectionHeader({required this.title, required this.action}); final String title, action; @override Widget build(BuildContext context) => Row(children: [Text(title, style: const TextStyle(fontSize: 21, fontWeight: FontWeight.w900, color: _ink)), const Spacer(), if (action.isNotEmpty) Text(action, style: const TextStyle(color: _purple, fontWeight: FontWeight.w700, fontSize: 13))]); }
class _Metric extends StatelessWidget { const _Metric({required this.value, required this.label, required this.icon}); final String value, label; final IconData icon; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.fromLTRB(10, 14, 10, 13), decoration: BoxDecoration(color: _surface, borderRadius: BorderRadius.circular(20), border: Border.all(color: const Color(0xFFEDEAF2))), child: Column(children: [Icon(icon, size: 20, color: _purple), const SizedBox(height: 8), Text(value, style: const TextStyle(fontSize: 21, fontWeight: FontWeight.w900, color: _ink)), const SizedBox(height: 2), Text(label, textAlign: TextAlign.center, style: const TextStyle(fontSize: 11, color: _muted, fontWeight: FontWeight.w600))])); }
class _TrainingCard extends StatelessWidget { const _TrainingCard({required this.title, required this.subtitle, required this.icon, required this.onTap}); final String title, subtitle; final IconData icon; final VoidCallback onTap; @override Widget build(BuildContext context) => Card(elevation: 0, margin: const EdgeInsets.only(bottom: 10), color: _surface, shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(20), side: const BorderSide(color: Color(0xFFEDEAF2))), child: InkWell(borderRadius: BorderRadius.circular(20), onTap: onTap, child: Padding(padding: const EdgeInsets.all(14), child: Row(children: [Container(width: 52, height: 52, decoration: BoxDecoration(color: const Color(0xFFEDEAFF), borderRadius: BorderRadius.circular(16)), child: Icon(icon, color: _purple, size: 27)), const SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontWeight: FontWeight.w800, fontSize: 16, color: _ink)), const SizedBox(height: 4), Text(subtitle, style: const TextStyle(color: _muted, fontSize: 13))])), const Icon(Icons.arrow_forward_ios_rounded, size: 16, color: _muted)])))); }

class _WorkoutsPage extends StatelessWidget { const _WorkoutsPage({required this.onStart}); final VoidCallback onStart; @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.fromLTRB(20, 22, 20, 28), children: [const Text('Train', style: TextStyle(fontSize: 30, fontWeight: FontWeight.w900, color: _ink)), const SizedBox(height: 6), const Text('Choose a movement and let Pose guide your form.', style: TextStyle(color: _muted)), const SizedBox(height: 24), _WorkoutHero(onStart: onStart), const SizedBox(height: 26), const Text('Movements', style: TextStyle(fontSize: 21, fontWeight: FontWeight.w900, color: _ink)), const SizedBox(height: 12), _TrainingCard(title: 'Squat form', subtitle: 'Real-time knee & movement feedback', icon: Icons.directions_run_rounded, onTap: onStart), _TrainingCard(title: 'Full body basics', subtitle: 'Beginner • guided movement', icon: Icons.accessibility_new_rounded, onTap: onStart)]); }
class _WorkoutHero extends StatelessWidget { const _WorkoutHero({required this.onStart}); final VoidCallback onStart; @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: _ink, borderRadius: BorderRadius.circular(26)), child: Row(children: [Container(width: 58, height: 58, decoration: BoxDecoration(color: _purple, borderRadius: BorderRadius.circular(18)), child: const Icon(Icons.play_arrow_rounded, color: Colors.white, size: 32)), const SizedBox(width: 15), const Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Your next session', style: TextStyle(color: Colors.white54, fontSize: 12, fontWeight: FontWeight.w700)), SizedBox(height: 4), Text('Start with squat form', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.w900)),])), IconButton(onPressed: onStart, icon: const Icon(Icons.arrow_forward_rounded, color: Colors.white))])); }

class _ProgressPage extends StatelessWidget { const _ProgressPage(); @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.fromLTRB(20, 22, 20, 28), children: [const Text('Progress', style: TextStyle(fontSize: 30, fontWeight: FontWeight.w900, color: _ink)), const SizedBox(height: 6), const Text('Small improvements add up.', style: TextStyle(color: _muted)), const SizedBox(height: 24), Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: _surface, borderRadius: BorderRadius.circular(26), border: Border.all(color: const Color(0xFFEDEAF2))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [const Text('Your journey', style: TextStyle(fontSize: 18, fontWeight: FontWeight.w900, color: _ink)), const SizedBox(height: 18), Row(children: const [Expanded(child: _ProgressStat('0', 'Sessions')), Expanded(child: _ProgressStat('0', 'Reps')), Expanded(child: _ProgressStat('—', 'Best score'))]), const SizedBox(height: 20), ClipRRect(borderRadius: BorderRadius.circular(20), child: const LinearProgressIndicator(value: 0, minHeight: 8)), const SizedBox(height: 10), const Text('Complete your first session to start tracking.', style: TextStyle(color: _muted, fontSize: 13))])), const SizedBox(height: 18), const _EmptyProgressCard()]); }
class _ProgressStat extends StatelessWidget { const _ProgressStat(this.value, this.label); final String value, label; @override Widget build(BuildContext context) => Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(value, style: const TextStyle(fontSize: 25, fontWeight: FontWeight.w900, color: _ink)), const SizedBox(height: 3), Text(label, style: const TextStyle(color: _muted, fontSize: 12))]); }
class _EmptyProgressCard extends StatelessWidget { const _EmptyProgressCard(); @override Widget build(BuildContext context) => Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(color: const Color(0xFFEFEAFF), borderRadius: BorderRadius.circular(24)), child: const Row(children: [Icon(Icons.auto_graph_rounded, color: _purple, size: 28), SizedBox(width: 14), Expanded(child: Text('Your first workout will unlock weekly trends, consistency and score history.', style: TextStyle(color: _ink, fontWeight: FontWeight.w600, height: 1.4)))])); }

class _ProfilePage extends StatelessWidget { const _ProfilePage(); @override Widget build(BuildContext context) => ListView(padding: const EdgeInsets.fromLTRB(20, 22, 20, 28), children: [const Text('Profile', style: TextStyle(fontSize: 30, fontWeight: FontWeight.w900, color: _ink)), const SizedBox(height: 6), const Text('Your training space.', style: TextStyle(color: _muted)), const SizedBox(height: 24), Container(padding: const EdgeInsets.all(20), decoration: BoxDecoration(gradient: const LinearGradient(colors: [Color(0xFF5E4AD7), Color(0xFF8B79FF)]), borderRadius: BorderRadius.circular(26)), child: Row(children: [Container(width: 58, height: 58, decoration: BoxDecoration(color: Colors.white.withValues(alpha: .18), shape: BoxShape.circle), child: const Icon(Icons.person_rounded, color: Colors.white, size: 32)), const SizedBox(width: 15), const Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text('Welcome to Pose', style: TextStyle(color: Colors.white, fontSize: 18, fontWeight: FontWeight.w900)), SizedBox(height: 4), Text('Train with better form', style: TextStyle(color: Colors.white70))])])), const SizedBox(height: 18), const _ProfileRow(icon: Icons.flag_outlined, title: 'Training goal', value: 'Build better movement'), const _ProfileRow(icon: Icons.accessibility_new_rounded, title: 'Focus', value: 'Form & technique'), const _ProfileRow(icon: Icons.shield_outlined, title: 'Privacy', value: 'On-device first'), const SizedBox(height: 18), Container(padding: const EdgeInsets.all(18), decoration: BoxDecoration(color: _surface, borderRadius: BorderRadius.circular(22), border: Border.all(color: const Color(0xFFEDEAF2))), child: const Row(children: [Icon(Icons.info_outline_rounded, color: _purple), SizedBox(width: 12), Expanded(child: Text('Pose is designed to give simple, understandable movement feedback.', style: TextStyle(color: _muted, height: 1.4)))]))]); }
class _ProfileRow extends StatelessWidget { const _ProfileRow({required this.icon, required this.title, required this.value}); final IconData icon; final String title, value; @override Widget build(BuildContext context) => Container(margin: const EdgeInsets.only(bottom: 10), padding: const EdgeInsets.all(16), decoration: BoxDecoration(color: _surface, borderRadius: BorderRadius.circular(20), border: Border.all(color: const Color(0xFFEDEAF2))), child: Row(children: [Icon(icon, color: _purple), const SizedBox(width: 14), Expanded(child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Text(title, style: const TextStyle(fontSize: 12, color: _muted)), const SizedBox(height: 3), Text(value, style: const TextStyle(fontWeight: FontWeight.w800, color: _ink))])), const Icon(Icons.chevron_right_rounded, color: _muted)])); }
