import 'package:flutter/material.dart';
import 'core/data/local_session_store.dart';
import 'core/data/session_model.dart';
import 'core/exercise/exercise_catalog.dart';
import 'features/pose_check/live_squat_check_page.dart';
import 'features/pose_check/live_exercise_check_page.dart';
import 'features/progress/progress_page.dart';

const purple=Color(0xFF6C5CE7),ink=Color(0xFF17151F),muted=Color(0xFF777382),bg=Color(0xFFF7F6FA);
void main()=>runApp(const PoseApp());
class PoseApp extends StatelessWidget{const PoseApp({super.key});@override Widget build(BuildContext c)=>MaterialApp(title:'Pose',debugShowCheckedModeBanner:false,theme:ThemeData(useMaterial3:true,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:purple)),home:const HomePage());}
class HomePage extends StatefulWidget{const HomePage({super.key});@override State<HomePage> createState()=>_HomePageState();}
class _HomePageState extends State<HomePage>{int index=0;final store=LocalSessionStore.instance;@override void initState(){super.initState();store.addListener(_refresh);store.load();}void _refresh(){if(mounted)setState((){});}Future<void> open(String id)async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>id=='squat'?const LiveSquatCheckPage():LiveExerciseCheckPage(exerciseId:id)));await store.load();if(mounted)setState((){});}@override void dispose(){store.removeListener(_refresh);super.dispose();}
@override Widget build(BuildContext c){final pages=[_Home(sessions:store.sessions,onStart:()=>open('squat')), _Train(onStart:open), ProgressPage(sessions:store.sessions),const _Profile()];return Scaffold(body:SafeArea(child:pages[index]),bottomNavigationBar:NavigationBar(selectedIndex:index,onDestinationSelected:(v)=>setState(()=>index=v),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home_rounded),label:'Home'),NavigationDestination(icon:Icon(Icons.fitness_center_outlined),selectedIcon:Icon(Icons.fitness_center_rounded),label:'Train'),NavigationDestination(icon:Icon(Icons.insights_outlined),selectedIcon:Icon(Icons.insights_rounded),label:'Progress'),NavigationDestination(icon:Icon(Icons.person_outline_rounded),selectedIcon:Icon(Icons.person_rounded),label:'Profile')]));}}
class _Home extends StatelessWidget{final List<WorkoutSession> sessions;final VoidCallback onStart;const _Home({required this.sessions,required this.onStart});@override Widget build(BuildContext c){final now=DateTime.now();final today=sessions.where((s)=>s.completedAt.year==now.year&&s.completedAt.month==now.month&&s.completedAt.day==now.day).length;final best=sessions.isEmpty?0:sessions.map((s)=>s.bestScore).reduce((a,b)=>a>b?a:b);return ListView(padding:const EdgeInsets.all(20),children:[const Text('TODAY',style:TextStyle(color:purple,fontSize:11,fontWeight:FontWeight.w900,letterSpacing:1.5)),const SizedBox(height:5),const Text('Ready to move?',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:22),Container(padding:const EdgeInsets.all(22),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF5140C4),Color(0xFF8B79FF)]),borderRadius:BorderRadius.circular(30)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('ON-DEVICE FORM CHECK',style:TextStyle(color:Colors.white70,fontSize:10,fontWeight:FontWeight.w900,letterSpacing:1.2)),const SizedBox(height:15),const Text('Move better.\nFeel stronger.',style:TextStyle(color:Colors.white,fontSize:30,fontWeight:FontWeight.w900,height:1.05)),const SizedBox(height:10),const Text('Camera-based movement feedback without sending your workout to a server.',style:TextStyle(color:Colors.white70,height:1.4)),const SizedBox(height:20),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:onStart,icon:const Icon(Icons.camera_alt_rounded),label:const Text('Check my squat'),style:FilledButton.styleFrom(backgroundColor:Colors.white,foregroundColor:Color(0xFF5140C4))))])),const SizedBox(height:25),const Text('Today',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:12),Row(children:[Expanded(child:_Metric('$today','Sessions')),const SizedBox(width:10),Expanded(child:_Metric('$best','Best score')),const SizedBox(width:10),Expanded(child:_Metric('${sessions.length}','All time'))]),const SizedBox(height:28),const Text('Train',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:12),_MiniExercise(item:exerciseCatalog[0],onTap:onStart),_MiniExercise(item:exerciseCatalog[1],onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>LiveExerciseCheckPage(exerciseId:'push_up')))),_MiniExercise(item:exerciseCatalog[2],onTap:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>LiveExerciseCheckPage(exerciseId:'lunge'))))]);}}
class _Metric extends StatelessWidget{final String v,l;const _Metric(this.v,this.l);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(vertical:16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(19),border:Border.all(color:const Color(0xFFEDEAF2))),child:Column(children:[Text(v,style:const TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:3),Text(l,style:const TextStyle(fontSize:10,color:muted,fontWeight:FontWeight.w700))]));}
class _MiniExercise extends StatelessWidget{final ExerciseCatalogItem item;final VoidCallback onTap;const _MiniExercise({required this.item,required this.onTap});@override Widget build(BuildContext c)=>Card(elevation:0,color:Colors.white,margin:const EdgeInsets.only(bottom:10),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(20),side:const BorderSide(color:Color(0xFFEDEAF2))),child:ListTile(onTap:onTap,contentPadding:const EdgeInsets.symmetric(horizontal:14,vertical:5),leading:Container(width:50,height:50,decoration:BoxDecoration(color:const Color(0xFFEDEAFF),borderRadius:BorderRadius.circular(15)),child:Icon(item.icon,color:purple)),title:Text(item.name,style:const TextStyle(fontWeight:FontWeight.w900,color:ink)),subtitle:Text(item.subtitle,style:const TextStyle(color:muted)),trailing:const Icon(Icons.arrow_forward_ios_rounded,size:16,color:muted)));}
class _Train extends StatelessWidget{final Future<void> Function(String) onStart;const _Train({required this.onStart});@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Train',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:6),const Text('Choose a movement and get live form feedback.',style:TextStyle(color:muted)),const SizedBox(height:25),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(color:ink,borderRadius:BorderRadius.circular(25)),child:const Row(children:[Icon(Icons.auto_awesome_rounded,color:Color(0xFFB9ADFF)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Phase 5',style:TextStyle(color:Colors.white54,fontSize:12)),SizedBox(height:4),Text('More movements, same simple flow.',style:TextStyle(color:Colors.white,fontSize:17,fontWeight:FontWeight.w900))]))])),const SizedBox(height:25),const Text('Movements',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:12),...exerciseCatalog.map((e)=>_TrainCard(item:e,onTap:()=>onStart(e.id))) ]);}}
class _TrainCard extends StatelessWidget{final ExerciseCatalogItem item;final VoidCallback onTap;const _TrainCard({required this.item,required this.onTap});@override Widget build(BuildContext c)=>Card(elevation:0,color:Colors.white,margin:const EdgeInsets.only(bottom:12),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(22),side:const BorderSide(color:Color(0xFFEDEAF2))),child:InkWell(borderRadius:BorderRadius.circular(22),onTap:onTap,child:Padding(padding:const EdgeInsets.all(16),child:Row(children:[Container(width:56,height:56,decoration:BoxDecoration(color:const Color(0xFFEDEAFF),borderRadius:BorderRadius.circular(17)),child:Icon(item.icon,color:purple,size:28)),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(item.name,style:const TextStyle(fontSize:17,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:4),Text(item.description,style:const TextStyle(color:muted,fontSize:13))])),const Icon(Icons.arrow_forward_ios_rounded,size:16,color:muted)]))));}
class _Profile extends StatelessWidget{const _Profile();@override Widget build(BuildContext c)=>ListView(padding:const EdgeInsets.all(20),children:[const Text('Profile',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:ink)),const SizedBox(height:6),const Text('Your training space.',style:TextStyle(color:muted)),const SizedBox(height:25),Container(padding:const EdgeInsets.all(20),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFF5140C4),Color(0xFF8B79FF)]),borderRadius:BorderRadius.circular(25)),child:const Row(children:[CircleAvatar(radius:29,backgroundColor:Colors.white24,child:Icon(Icons.person_rounded,color:Colors.white,size:30)),SizedBox(width:14),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Welcome to Pose',style:TextStyle(color:Colors.white,fontSize:18,fontWeight:FontWeight.w900)),SizedBox(height:4),Text('Train with better form',style:TextStyle(color:Colors.white70))])])),const SizedBox(height:18),const _ProfileRow(Icons.flag_outlined,'Training goal','Build better movement'),const _ProfileRow(Icons.accessibility_new_rounded,'Focus','Form & technique'),const _ProfileRow(Icons.shield_outlined,'Privacy','On-device first')]);}
class _ProfileRow extends StatelessWidget{final IconData i;final String t,v;const _ProfileRow(this.i,this.t,this.v);@override Widget build(BuildContext c)=>Container(margin:const EdgeInsets.only(bottom:10),padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:const Color(0xFFEDEAF2))),child:Row(children:[Icon(i,color:purple),const SizedBox(width:14),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(color:muted,fontSize:12)),const SizedBox(height:3),Text(v,style:const TextStyle(color:ink,fontWeight:FontWeight.w800))])),const Icon(Icons.chevron_right_rounded,color:muted)]));}
